CREATE DATABASE MANYTOMANY
USE MANYTOMANY

CREATE TABLE Roles (
Id INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(100)NOT NULL 
)

CREATE TABLE Users (
Id INT PRIMARY KEY IDENTITY,
Username VARCHAR(100)NOT NULL UNIQUE,
Password VARCHAR(100) UNIQUE,
RolesId INT FOREIGN KEY REFERENCES Roles(Id)
)
SELECT u.Username,r.Name FROM Roles AS r
JOIN Users AS u
ON u.RolesId=r.Id
